language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
  fast_finish: true

services:
  - redis-server

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo echo "127.0.0.1 busque-redis busque-php" >> /etc/hosts
  - composer selfupdate

install:
  - composer install --prefer-source --no-interaction

script:
  - vendor/squizlabs/php_codesniffer/scripts/phpcs --standard=PSR2 src
  - vendor/phpspec/phpspec/bin/phpspec run -v --config=phpspec.yml --format=pretty
  - vendor/behat/behat/bin/behat -v --profile default
  - vendor/behat/behat/bin/behat -v --profile predis
