language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
  fast_finish: true

before_install:
  - composer selfupdate

install:
  - composer install --prefer-source --no-interaction --dev

script:
   - vendor/bin/phpspec run --format=pretty
