language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
  fast_finish: true

before_install:
  - composer selfupdate

install:
  - composer install --prefer-source --no-interaction

script:
   - vendor/phpspec/phpspec/bin/phpspec run --config=phpspec.yml --format=pretty
