version: "2"
services:
    php:
        container_name: busque-php
        image: mgdigital/busque-php:latest
        build: ./php
        volumes:
            - ../:/busque/
        working_dir: /busque
        ports:
            - "9000:9000"
        depends_on:
            - redis
        networks:
            - front
    redis:
        container_name: busque-redis
        image: mgdigital/busque-redis:latest
        build: ./redis
        ports:
            - "6379:6379"
        networks:
            - front
networks:
    front:
